### ISSUE TITLE
Need a simple tutorial how to using View System from Start

### ISSUE THREAD

**Issue by takaaptech** [UniGameTeam/UniGame.ViewSystem.Examples#1]
Hi @Mefodei !
I now can download and run all the examples correctly. The example shows very impressive performance and nice effect.
Now for use in a real game, could you please add a simple document  on how to create some basic panels like this:
 - Menu Panel with a Play button and a Setting Button
 - Setting Panel with a close button
 - Game Panel with a back button (Go back to Menu Panel)
 - Play Button can trigger load new unity scene (Play Scene) - So we can demo the power of View System in multi Scenes

All Panels using sprite and sprites are packed into sprite atlas, We also need help on how to using addressable with sprite atlas.

Thank you so much for this awesome System!

**Comment by Mefodei** [comment]
That a good point. I will try update examples asap

**Comment by takaaptech** [comment]
Thank @Mefodei That would be awesome for us to learn and apply the System!

**Comment by Mefodei** [comment]
@takaaptech  add new example with more complex ui flow. Package README update in progress
